site_tasty:
    resource: "@SiteTastyBundle/Controller"
    type:     annotation
    prefix:   /

bundles_user_admin:
    resource: "@BundlesUserBundle/Resources/config/routing/admin_security.xml"
    prefix:   /admin

bundles_user:
    resource: "@BundlesUserBundle/Resources/config/routing/security.xml"
    
index_page:
    path:      /
    defaults:  { _controller: SiteTastyBundle:Main:homepage }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile